---
dist: xenial
sudo: false

language: bash

services:
   docker

before_install:
   - docker build -t cf_icd_plugin .
   - docker run -it --name cf_icd_plugin cf_icd_plugin tail -F -n0 /etc/hosts
   - docker ps -a
   - docker cp cf_icd_plugin:/app/icd/bin ./build_bin

install:
   - ls -al .
   - ls -al ./build_bin
