---
dist: xenial
sudo: false

language: bash

services:
   docker

before_install:
   - docker build -t cf_icd_plugin .
   - docker create --name cf_icd_plugin cf_icd_plugin tail -F -n0 /etc/hosts
   - docker start cf_icd_plugin
   - docker cp cf_icd_plugin:/app/icd/bin ./build_bin

install:
   - ls -al ./build_bin

deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  file:
    - ./build_bin/icd_osx
    - ./build_bin/icd_win64.exe
    - ./build_bin/icd_linux64
  skip_cleanup: true
  on:
    tags: true
