---
dist: xenial
sudo: false

language: bash

services:
   docker

install:
   - ./build

deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  file:
    - ./build_bin/icd_osx
    - ./build_bin/icd_win64.exe
    - ./build_bin/icd_linux64
  skip_cleanup: true
  on:
    tags: true
